### PR TITLE
Install bash added

### PR DESCRIPTION
**Pull request by dnsoumik**

### CODE REVIEW

**Comment by adamplumb** [comment]
I appreciate you trying to help here but unfortunately I don't think we can use this. Everyone's system is different and not everyone is using a Debian based system. 

We could possibly add it to the cli client readme as an example for manual installation if you want to pursue it further.

**Comment by dnsoumik** [comment]
That will be great if you added to README if I can provide Fedora and BSD scripts also in future.

**Comment by dnsoumik** [comment]
That will be great if you add in README, I can provide Fedora and BSD scripts also in future.

**Comment by CloCkWeRX** [comment]
Closing for the moment, but an updated PR to the readme is most welcome

**Pull request closed without merging**
