### PR TITLE
Different package names for newer ubuntu versions

### PR DESCRIPTION
**Pull request by amcolash**
In newer versions of ubuntu (at least 16.04 - 17.10) I was unable to follow the directions in the README. I have updated the package names accordingly.

### CODE REVIEW

**Comment by kwill** [comment]
This applies to contemporary versions of any Debian-based distro, so I'd suggest:
* update the "Debian" section rather than adding a "newer Ubuntu" section
* simply remove old package names rather than maintaining references to them (ie. reduce the support burden on this project - anyone wanting to install new RabbitVCS on and old distro could post a query or look up package names themselves)

**Comment by amcolash** [comment]
I have updated the pull request based on your suggestions. Thank you for the pointers!

**Comment by PaulMEdwards** [comment]
For the Nautilus extension, the dependency "nautilus-python" is now known as "python-nautilus" on Ubuntu 18.04.03 LTS...

**Review by CloCkWeRX — CHANGES_REQUESTED** [review]
Conflicts

**Comment by CloCkWeRX** [comment]
Superceded

**Pull request closed without merging**
