### PR TITLE
Fixing https://github.com/rabbitvcs/rabbitvcs/issues/70

### PR DESCRIPTION
**Pull request by abaheti**
This is an issue with the export where on selecting the partition, it deletes all the files on that partition. Even after deleting all the files, the export fails to get the file.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
So this was originally brought in with c42f5b04b69f25791a1142593be65c3d38127a36 and 7a3eae0a13b549c036da0a4aabcc25a286b8c025.

Can you test exporting over an existing export with this change?

**Comment by CloCkWeRX** [comment]
#70

**Comment by abaheti** [comment]
I have tested this. The files/folder exported will be re-written.

That seems like an acceptable implementation rather than deleting all the folders/files if the root of the partition is selected.

**Comment by CloCkWeRX** [comment]
I'm not too certain, not having tested it myself; but I suppose the worst case is we get the failure to clean up exports prior to re-exporting; which is less of a pain that losing files.

**Comment by CloCkWeRX** [comment]
#70

**Pull request merged**
